name: PR Video

on:
  pull_request:
    types: [labeled]

jobs:
  generate-video:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'generate-video'
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Generate PR Video
        uses: jmrobles/prvideo@v1
        with:
          api-key: ${{ secrets.PRVIDEO_API_KEY }}
